// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77sZLB0Ia2F472ip2bj-YPvZVKwWM9WA',
    appId: '1:20897788348:web:5a08c38bd1dec9febc7bb9',
    messagingSenderId: '20897788348',
    projectId: 'quickbill-2a76b',
    authDomain: 'quickbill-2a76b.firebaseapp.com',
    storageBucket: 'quickbill-2a76b.firebasestorage.app',
    measurementId: 'G-5K90Z0RTK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX8aP5N_2zgIFNS22EtU_WCNX04bUN3ws',
    appId: '1:20897788348:android:3638803f4f6c5a89bc7bb9',
    messagingSenderId: '20897788348',
    projectId: 'quickbill-2a76b',
    storageBucket: 'quickbill-2a76b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhPxIcOr15QhjlBQC_D2HVxxS6EiwRLlc',
    appId: '1:20897788348:ios:804c1d26ca61f4f1bc7bb9',
    messagingSenderId: '20897788348',
    projectId: 'quickbill-2a76b',
    storageBucket: 'quickbill-2a76b.firebasestorage.app',
    iosBundleId: 'com.example.quickbill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhPxIcOr15QhjlBQC_D2HVxxS6EiwRLlc',
    appId: '1:20897788348:ios:804c1d26ca61f4f1bc7bb9',
    messagingSenderId: '20897788348',
    projectId: 'quickbill-2a76b',
    storageBucket: 'quickbill-2a76b.firebasestorage.app',
    iosBundleId: 'com.example.quickbill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC77sZLB0Ia2F472ip2bj-YPvZVKwWM9WA',
    appId: '1:20897788348:web:58da014920af5f83bc7bb9',
    messagingSenderId: '20897788348',
    projectId: 'quickbill-2a76b',
    authDomain: 'quickbill-2a76b.firebaseapp.com',
    storageBucket: 'quickbill-2a76b.firebasestorage.app',
    measurementId: 'G-TM09BZ6L8D',
  );
}
